### ISSUE TITLE
timeout of 5s exceeded

### ISSUE THREAD

**Issue by cdarau** [cronitorio/cronitor-js#30]
I'm getting this error:
```
Error: timeout of 5000ms exceeded
    at createError (/home/bitnami/<project-name>/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/home/bitnami/<project-name>/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest.EventEmitter.emit (domain.js:506:15)
    at Timeout.<anonymous> (/home/bitnami/<project-name>/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
    config: {
      url: '<url>',
      method: 'get',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'User-Agent': 'cronitor-js',
        Authorization: 'Basic <token>'
      },
      params: {
        state: 'run',
        env: '<env>>',
        message: '<message>>',
        series: '<series>'
      },
      baseURL: '',
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      paramsSerializer: [Function: paramsSerializer],
      timeout: 5000,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      },
      data: undefined
    },
    code: 'ECONNABORTED',
    request: Writable {
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        afterWriteTickInfo: null,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object]
      },
      writable: true,
      _events: [Object: null prototype] {
        response: [Function: handleResponse],
        error: [Function: handleRequestError],
        socket: [Function: destroyOnTimeout]
      },
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: {
        maxRedirects: 21,
        maxBodyLength: 10485760,
        protocol: 'https:',
        path: '<path>>',
        method: 'GET',
        headers: [Object],
        agent: undefined,
        agents: [Object],
        auth: undefined,
        hostname: 'cronitor.link',
        port: null,
        nativeProtocols: [Object],
        pathname: '<pathname>',
        search: '<search>'
      },
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: ClientRequest {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header: '<_header>',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        method: 'GET',
        insecureHTTPParser: undefined,
        path: '<path>',
        _ended: false,
        res: null,
        aborted: true,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: [HTTPParser],
        maxHeadersCount: null,
        reusedSocket: false,
        _redirectable: [Circular],
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype]
      },
      _currentUrl: '<_currentUrl>',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    response: undefined,
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
```
How can I change the timeout of 5000ms I'm seeing listed under this error. I see no way to do that.

**Comment by aflanagan** [comment]
Hi @cdarau, this is now configurable in 2.3.4 release. You can either pass `timeout` in the config options, or set the `CRONITOR_TIMEOUT` env var.

**Comment by cdarau** [comment]
Great news! Thank you, @aflanagan !
